### ISSUE TITLE
Fatal error - encoding problem?

### ISSUE THREAD

**Issue by peter-hank** [JanHelbling/jhSitemapgenerator#1]
Hey Jan,

trying to run your script but unfortunately I'm getting:

> File "/usr/local/bin/jhSitemapgenerator.py", line 38
> SyntaxError: Non-ASCII character '\xc2' in file /usr/local/bin/jhSitemapgenerator.py on line 38, but no > encoding declared; see http://www.python.org/peps/pep-0263.html for details

Any ideas how to fix?

**Comment by JanHelbling** [comment]
try it now again, i have added the encoding line to the script ;)
